<div class="par iparys_inherited">
  <div class="global-header">
    <nav>
      <ul id="wb-tphp" class="wb-init wb-disable-inited">
        <li class="wb-slc">
          <a class="wb-sl" href="#wb-cont">Skip to main content</a>
        </li>
        <li class="wb-slc">
          <a class="wb-sl" href="#wb-info">Skip to &#34;About government&#34;</a>
        </li>
      </ul>
    </nav>

    <header role="banner">
      <div id="wb-bnr" class="container">
        <div class="row">
          <section id="wb-lng" class="col-xs-3 col-sm-12 pull-right text-right">
            <h2 class="wb-inv">Language selection</h2>
            <div class="row">
              <div class="col-md-12">
                <ul class="list-inline mrgn-bttm-0">
                  <li>
                    <a lang="fr" href="catalog.aspx?l=E">
                      <span class="hidden-xs">English</span>
                      <abbr title="English" class="visible-xs h3 mrgn-tp-sm mrgn-bttm-0 text-uppercase">fr</abbr>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </section>

          <div class="brand col-xs-9 col-sm-5 col-md-4" property="publisher" resource="#wb-publisher" typeof="GovernmentOrganization">
            <a href="https://www.canada.ca/fr.html" property="url">
              <img src="https://www.canada.ca/etc/designs/canada/wet-boew/assets/sig-blk-fr.svg" alt="Government of Canada" property="logo"/>
              <span class="wb-inv">
                /
                <span lang="fr">Gouvernement du Canada</span>
              </span>
            </a>
            <meta property="name" content="Government of Canada"/>
            <meta property="areaServed" typeof="Country" content="Canada"/>
            <link property="logo" href="https://www.canada.ca/etc/designs/canada/wet-boew/assets/wmms-blk.svg"/>
          </div>

          <section id="wb-srch" class="col-lg-offset-4 col-md-offset-4 col-sm-offset-2 col-xs-12 col-sm-5 col-md-4">
            <h2>Search</h2>
            <form action="https://www.canada.ca/fr/sr/srb.html" method="get" name="cse-search-box" role="search">
              <div class="form-group wb-srch-qry">
                <label for="wb-srch-q" class="wb-inv">Rechercher dans Canada.ca</label>
                <input id="wb-srch-q" list="wb-srch-q-ac" class="wb-srch-q form-control" name="q" type="search" value="" size="34" maxlength="170" placeholder="Rechercher dans Canada.ca"/>
                <datalist id="wb-srch-q-ac">
                </datalist>
              </div>
              <div class="form-group submit">
                <button type="submit" id="wb-srch-sub" class="btn btn-primary btn-small" name="wb-srch-sub">
                  <span class="glyphicon-search glyphicon"></span>
                  <span class="wb-inv">Rechercher</span>
                </button>
              </div>
            </form>
          </section>
        </div>
      </div>

      <HR />
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <nav class="gcweb-menu wb-init gcweb-menu-inited" typeof="SiteNavigationElement" id="wb-auto-2">
              <h2 class="wb-inv">Menu</h2>
              <button type="button" aria-haspopup="true" aria-expanded="false">
                <span class="wb-inv">Main </span>Menu <span class="expicon glyphicon glyphicon-chevron-down"></span>
              </button>
              <ul role="menu" aria-orientation="vertical" data-ajax-replace="https://www.canada.ca/content/dam/canada/sitemenu/sitemenu-v2-fr.html">
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/en/services/jobs.html">Emplois et milieu de travail</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/en/services/immigration-citizenship.html">Immigration et citoyennet&eacute;</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://voyage.gc.ca/">Voyage et tourisme</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/fr/services/entreprises.html">Entreprises et industrie</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/en/services/benefits.html">Prestations</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/fr/services/sante.html">Sant&eacute;</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/fr/services/impots.html">Imp&ocirc;ts</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/fr/services/environnement.html">Environnement et ressources naturelles</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/fr/services/defense.html">S&eacute;curit&eacute; nationale et d&eacute;fense</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/fr/services/culture.html">Culture, histoire et sport</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/fr/services/police.html">Services de police, justice et urgences</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/en/services/transport.html">Transport et infrastructure</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://international.gc.ca/world-monde/index.aspx?lang=fra">Canada et le monde</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/fr/services/finance.html">Argent et finances</a>
                </li>
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="https://www.canada.ca/fr/services/science.html">Science et innovation</a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
      <nav role="navigation" id="wb-bc" class="" property="breadcrumb">
        <h2>You are here:</h2>
        <div class="container">
          <div class="row">
            <ol class="breadcrumb">
              <li>
                <a href="https://canada.ca/en/index.html">Home</a>
              </li>
              <li>
                <a href="https://www.aadnc-aandc.gc.ca/eng/">RCAANC/SAC</a>
              </li>
            </ol>
          </div>
        </div>
      </nav>
    </header>
  </div>
</div>
</NOSCRIPT>