		<!-- Load closure template scripts -->
		<script type="text/javascript" src="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_26/cdts/compiled/soyutils.js"></script>
		<script type="text/javascript" src="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_26/cdts/compiled/wet-fr.js"></script>
		<noscript>
			<!-- Write closure fall-back static file -->
			<!-- /ROOT/etc/designs/canada/cdts/gcweb/v4_0_26/cdts/static/refTop.html -->

      <!-- Write closure fall-back static file -->
      <!-- /ROOT/etc/designs/canada/cdts/gcweb/v4_0_26/cdts/static/refTop.html -->

      <link rel="stylesheet prefetch" href="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_26/css/theme.min.css"  />
      <link rel="stylesheet" href="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_26/cdts/cdtsfixes.css"  />

      
              
		</noscript>
		<!-- Write closure template -->
		<script type="text/javascript">
		    document.write(wet.builder.refTop({
		    }));
		</script>