				<script type="text/javascript">
				    var secondarymenu = document.getElementById("wb-sec");
				    secondarymenu.innerHTML = wet.builder.secmenu({
				        sections: [{

				            // Rinse and repeat
				            sectionName: "Publication Catalogue",
				            sectionLink: "catalog.aspx",
				            newWindow: false,
				            menuLinks: [{
				                href: "search.aspx",
				                text: "Search"
				            }, {
				                href: "advsearch.aspx",
				                text: "Advanced Search"
				            }, {
				                href: "cart.aspx",
				                text: "Cart"
				            }, {
				                href: "shipping2.aspx",
				                text: "Shipping Details"
				            }]
				        }]
				    });
				</script>