<noscript>
  <br />
  <p>

    <a href="catalog.aspx?l=E">
      <%=oLang.GetLabel("PublicationsCatalog")%>
    </a>
    <ul >
      <li>
        <a href="search.aspx?l=E" >
          <%=oLang.GetLabel("Search2")%>
        </a>
      </li>
      <li>
        <a href="advsearch.aspx?l=E" >
          <%=oLang.GetLabel("AdvTitle")%>
        </a>
      </li>
      <li>
        <a href="cart.aspx?l=E">
          <%=oLang.GetLabel("Cart")%>
        </a>
      </li>
      <li>
        <a href="shipping2.aspx?l=E" >
          <%=oLang.GetLabel("ShippingDetails")%></a>
      </li>
    </ul>
  </p>

</noscript>

