<noscript>
  <br />
  <p>
    <a href="catalog.aspx?l=F">
      <%=oLang.GetLabel("PublicationsCatalog")%>
    </a>
    <ul >
      <li>
        <a href="search.aspx?l=F" >
          <%=oLang.GetLabel("Search2")%>
        </a>
      </li>
      <li>
        <a href="advsearch.aspx?l=F" >
          <%=oLang.GetLabel("AdvTitle")%>
        </a>
      </li>
      <li>
        <a href="cart.aspx?l=F">
          <%=oLang.GetLabel("Cart")%>
        </a>
      </li>
      <li>
        <a href="shipping2.aspx?l=F" >
          <%=oLang.GetLabel("ShippingDetails")%>
        </a>
      </li>
    </ul>
  </p>

</noscript>