<!-- FooterStart -->
<nav role="navigation">
  <div id="gcwu-sft">
    <h3>Site footer</h3>
    <div id="gcwu-sft-in">
      <div id="gcwu-tctr">
        <ul>
          <li class="gcwu-tc">
            <a href="http://www.aadnc-aandc.gc.ca/eng/1290197332920" rel="license">Terms and conditions</a>
          </li>
          <li class="gcwu-tr">
            <a href="http://www.aadnc-aandc.gc.ca/prodis/index-eng.asp">Transparency</a>
          </li>

        </ul>
      </div>
      <div class="clear"></div>
      <section>
        <div class="span-2">
          <h4 class="gcwu-col-head">
            <a href="http://www.aadnc-aandc.gc.ca/eng/1100100010023">About us</a>
          </h4>
          <ul>
            <li>
              <a href="http://www.aadnc-aandc.gc.ca/eng/1100100010023">Our Mandate</a>
            </li>
            <li>
              <a href="http://www.aadnc-aandc.gc.ca/eng/1361550152840">The Minister</a>
            </li>
          </ul>
        </div>
      </section>
      <section>
        <div class="span-2">
          <h4 class="gcwu-col-head">
            <a href="http://www.aadnc-aandc.gc.ca/eng/1291132820288">Contact us</a>
          </h4>
          <ul>
            <li>
              <a href="http://sage-geds.tpsgc-pwgsc.gc.ca/cgi-bin/direct500/eng/TE?FN=index.htm">Phone numbers</a>
            </li>
            <!--<li><a href="#">Office locations</a></li>-->
          </ul>
        </div>
      </section>
      <section>
        <div class="span-2">
          <h4 class="gcwu-col-head">
            <a href="http://www.aadnc-aandc.gc.ca/eng/1100100014740">News</a>
          </h4>
          <ul>
            <li>
              <a href="http://www.aadnc-aandc.gc.ca/eng/1393261289317">News releases</a>
            </li>
            <li>
              <a href="http://www.aadnc-aandc.gc.ca/eng/1393611341080">Media advisories</a>
            </li>
            <li>
              <a href="http://www.aadnc-aandc.gc.ca/eng/1356966259951">Speeches / Speaking Notes</a>
            </li>
            <li>
              <a href="http://www.aadnc-aandc.gc.ca/eng/1362082869791">Photo Gallery</a>
            </li>
            <li>
              <a href="http://www.aadnc-aandc.gc.ca/eng/1100100016513">e-Bulletin</a>
            </li>
          </ul>
        </div>
      </section>
      <section>
        <div class="span-2">
          <h4 class="gcwu-col-head">
            <a href="http://www.aadnc-aandc.gc.ca/eng/1291145785920">Stay connected</a>
          </h4>
          <ul>
            <li>
              <a rel="external" href="http://www.facebook.com/AANDCanada">Facebook</a>
            </li>
            <li>
              <a rel="external" href="http://twitter.com/AANDCanada">Twitter</a>
            </li>
            <li>
              <a rel="external" href="http://www.youtube.com/AANDCanada">YouTube</a>
            </li>
            <li>
              <a rel="external" href="http://www.flickr.com/aandcanada">Flickr</a>
            </li>
            <li>
              <a href="http://www.aadnc-aandc.gc.ca/eng/1291225661056">Feeds</a>
            </li>
          </ul>
        </div>
      </section>
    </div>
  </div>
</nav>

<nav role="navigation">
  <div id="gcwu-gcft">
    <h3>Government of Canada footer</h3>
    <div id="gcwu-gcft-in">
      <div id="gcwu-gcft-fip">
        <ul>
          <li>
            <a rel="external" href="http://healthycanadians.gc.ca/index-eng.php">
              <span>HEALTH</span><br />
              healthycanadians.gc.ca
            </a>
          </li>
          <li>
            <a rel="external" href="http://www.voyage.gc.ca/index-eng.asp">
              <span>TRAVEL</span><br />
              travel.gc.ca
            </a>
          </li>
          <li>
            <a rel="external" href="http://www.servicecanada.gc.ca/eng/home.shtml">
              <span>SERVICE CANADA</span><br />
              servicecanada.gc.ca
            </a>
          </li>
          <li>
            <a rel="external" href="http://www.jobbank.gc.ca/intro-eng.aspx">
              <span>JOBS</span><br />
              jobbank.gc.ca
            </a>
          </li>
          <li>
            <a rel="external" href="http://actionplan.gc.ca/en">
              <span>Economy</span><br />
              actionplan.gc.ca
            </a>
          </li>
          <li id="gcwu-gcft-ca">
            <div>
              <a rel="external" href="http://www.canada.gc.ca/menu-eng.html">Canada.gc.ca</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>