<section>

  <h3 class="top-section">
    <a href="../publication/catalog.aspx?l=F" class="ui-link">
      <%=oLang.GetLabel("PublicationsCatalog")%>
    </a>
  </h3>
  <div class="innerLeftMenu">
    <ul>
      <li class="top-level">
        <a href="../publication/search.aspx?l=F" class="ui-link">
          <%=oLang.GetLabel("Search2")%>
        </a>
      </li>

      <li class="top-level">
        <a href="../publication/Advsearch.aspx?l=F" class="ui-link">
          <%=oLang.GetLabel("AdvTitle")%>
        </a>
      </li>

      <li class="top-level">
        <a href="../publication/cart.aspx?l=F" class="ui-link">
          <%=oLang.GetLabel("Cart")%>
        </a>
      </li>

      <li class="top-level">
        <a href="../publication/shipping.aspx?l=F" class="ui-link">
          <%=oLang.GetLabel("ShippingDetails")%>
        </a>
      </li>

    </ul>
  </div>

</section>
